In [1]:
import inspect

# NumPyの使い方

## NumPy とは
---
多次元配列の演算、特に線形代数などの科学計算の基本的な機能を提供。

## NumPy の使い方

### インポート
---
慣習として`np`という名前をつける。

In [2]:
import numpy as np

### 配列の作成
---
`numpy.array`に Python の配列を渡す。

In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [4]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

連続する整数の配列は`numpy.arange`を使用する。

In [5]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### 練習問題

10 から 49 までの整数が並んだベクトル (1 次元配列) を作成 ([100 numpy exercises #7](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

ある区間を等間隔に分割した配列を作成するには`numpy.linspace`を使用する。

In [7]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [8]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

初期値 0 の配列を作成するには`numpy.zeros`を使用する。

In [9]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

###### 練習問題

0が10個並んだベクトルを作成 ([100 numpy exercises #3](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

初期値 1 の配列を作成するには`numpy.ones`を使用する。

In [11]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [12]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

任意の初期値で埋められた配列を作成するには`numpy.full`を使用する。

In [13]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values to

In [14]:
np.full((2, 3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

`numpy.*_like`で既存の配列と同じサイズの配列を作成可能。

In [15]:
[
    f[0]
    for f in inspect.getmembers(np, inspect.isfunction)
    if f[0].endswith('_like')
]

['empty_like', 'full_like', 'ones_like', 'zeros_like']

In [16]:
m = np.array([[1, 2, 3], [4, 5, 6]])
z = np.zeros_like(m)
z

array([[0, 0, 0],
       [0, 0, 0]])

### 配列の操作
---
基本的には Python の配列と同様の方法で値の変更やスライシングが可能。

In [17]:
a = np.arange(5)
a[2] = 9
a

array([0, 1, 9, 3, 4])

In [18]:
a[-2:]

array([3, 4])

###### 練習問題

0 が 10 個並んだベクトルを作成し、 5 番目の要素を 1 にする ([100 numpy exercises #6](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

###### 練習問題

ベクトル要素の順番を逆にする ([100 numpy exercises #8](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

2 行 3 列目の値を指定するには以下のように行う。

In [19]:
m = np.array([[1, 2, 3], [4, 5, 6]])
m[1, 2]

6

行単位や列単位でも指定可能。

In [20]:
m[1]

array([4, 5, 6])

In [21]:
m[:, 2]

array([3, 6])

###### 練習問題

10x10 の外周の数値が 1 で内側の数値が 0 の行列を作成 ([100 numpy exercises #15](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

$$
\left(\begin{matrix}
    1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\
    1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1
\end{matrix}\right)
$$

行列 (2 次元配列) の転置 (行と列の入れ替え) は T 属性で取得可能。

In [22]:
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])

配列のサイズは shape 属性で取得可能。

In [23]:
m.shape

(2, 3)

配列のサイズ変更は`numpy.reshape`を使用する。

In [24]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [25]:
m.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

配列の要素数は size 属性で取得可能。

In [26]:
m.size

6

###### 練習問題

0 から 8 までの整数が並んだ 3x3 行列を作成 ([100 numpy exercises #9](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb))

### 要素同士の演算
---
同じサイズの配列同士なら、その要素同士の演算は通常の演算子で可能。

In [27]:
a = np.arange(6).reshape((2, 3))
b = np.arange(4, 10).reshape((2, 3))
print('a=')
print(a)
print('b=')
print(b)

a=
[[0 1 2]
 [3 4 5]]
b=
[[4 5 6]
 [7 8 9]]


In [28]:
a + b

array([[ 4,  6,  8],
       [10, 12, 14]])

In [29]:
a * b

array([[ 0,  5, 12],
       [21, 32, 45]])